In [2]:
# 1) Less Memory 2) Fast 3) Convinient

In [4]:
import numpy as np
import time
import sys


l=range(1000)

#takes less memory
array=np.arange(1000)

print(sys.getsizeof(5)*len(l))
print(array.size*array.itemsize)

28000
4000


In [15]:
size=100000

In [16]:
l1=range(size)
l2=range(size)


#executes very fast
ar1=np.arange(size)
ar2=np.arange(size)

start=time.time()
result=[(x+y) for x,y in zip(l1,l2)]
print("Python list took ", (time.time()-start)*1000)

start=time.time()
result=ar1+ar2
print("Numpy array took",(time.time()-start)*1000)

Python list took  33.00952911376953
Numpy array took 7.999658584594727


In [18]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
a1+a2

array([5, 7, 9])

a1-a2

In [19]:
a1/a2

array([0.25, 0.4 , 0.5 ])

In [20]:
a1*a2

array([ 4, 10, 18])