In [1]:
print("Hello World")

Hello World


In [2]:
import numpy as np


In [3]:
myarr=np.array([[1,2,3,4,4]],np.int64)

In [4]:
print(myarr)

[[1 2 3 4 4]]


In [5]:
myarr[0,1]

2

In [6]:
myarr.shape


(1, 5)

In [7]:
myarr.dtype


dtype('int64')

In [8]:
myarr


array([[1, 2, 3, 4, 4]], dtype=int64)

In [9]:
myarr[0,1]=32

In [10]:
myarr

array([[ 1, 32,  3,  4,  4]], dtype=int64)

In [11]:
# 5 Methods to create numpy array



**Array Creation : Conversion from other Python Structures **

In [12]:
listarray=np.array([[1,2,3],[3,4,56],[5,6,3]])
listarray

array([[ 1,  2,  3],
       [ 3,  4, 56],
       [ 5,  6,  3]])

In [13]:
listarray.shape


(3, 3)

In [14]:
listarray.size #will give no. of elements in array

9

In [15]:
listarray.dtype


dtype('int32')

In [16]:
#zeros create matrix or array 2 dimensional

zeros=np.zeros((2,5))
zeros


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
zeros.shape


(2, 5)

In [19]:
zeros.size

10

In [20]:
zeros.dtype

dtype('float64')

In [21]:
rng=np.arange(16)
rng


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [22]:
# linspace 1=>starting no. 2=>ending no. 3=>how many no. u want   --will give equally spaced elements
lspace=np.linspace(1,9,4)
lspace

array([1.        , 3.66666667, 6.33333333, 9.        ])

In [83]:
empty=np.empty((4,6)) #empty gives empty array with random no.s
empty

array([[4.67296746e-307, 1.69121096e-306, 1.15710427e-306,
        1.78019082e-306, 7.56595733e-307, 1.33511018e-306],
       [1.33511969e-306, 6.23037996e-307, 6.23053954e-307,
        9.34609790e-307, 8.45593934e-307, 9.34600963e-307],
       [1.86921143e-306, 6.23061763e-307, 8.90104239e-307,
        6.89804132e-307, 1.22387465e-307, 1.42418172e-306],
       [2.04712906e-306, 7.56589622e-307, 1.11258277e-307,
        8.90111708e-307, 2.11389826e-307, 1.11260619e-306]])

In [24]:
emp_like=np.empty_like(lspace) # empty elements create kreyga with previous array to increase efficiency
emp_like

array([1.        , 3.66666667, 6.33333333, 9.        ])

In [25]:
ide=np.identity(45) # will give unit matrix of 45*45
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [26]:
ide.shape

(45, 45)

In [27]:
ide.size

2025

In [28]:
arr=np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [29]:
arr.reshape(3,33) #will give resize of array but 33*3 should be == 99

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [31]:
arr=arr.ravel()
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [32]:
arr.shape


(99,)

In [33]:
arr.size

99

In [34]:
x=[[1,2,3],[4,5,6],[7,8,9]]
ar=np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
ar.shape

(3, 3)

In [36]:
ar.size

9

In [37]:
ar.sum(axis=0) #will give the sum of columns

array([12, 15, 18])

In [38]:
ar.sum(axis=1) # will give the sum of rows

array([ 6, 15, 24])

In [39]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [41]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
for items in ar.flat: # will print all elements of 2D array
    print(items)

1
2
3
4
5
6
7
8
9


In [43]:
ar.ndim # will give no. of dimensions

2

In [44]:
ar.nbytes # how many bytes the array is consuming

36

In [45]:
one=np.array([1,3,5,4,433])
one

array([  1,   3,   5,   4, 433])

In [46]:
one.argmax() #will give the index of max element

4

In [47]:
one.argmin() #will give the index of max element

0

In [48]:
one.argsort() # will tell that index no. should be at this position inorder to sort

array([0, 1, 3, 2, 4], dtype=int64)

In [49]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
ar.argmin() # ye array ko pura seedha krkyphir check kry ga ke konsy index pr min no ha

0

In [51]:
ar.argmax()# ye array ko pura seedha krkyphir check kry ga ke konsy index pr max no ha

8

In [52]:
ar.argmax(axis=0) #will check column wise

array([2, 2, 2], dtype=int64)

In [53]:
ar.argmin(axis=1) #will check row wise

array([0, 0, 0], dtype=int64)

In [54]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [55]:
ar.argmin()#will give index

0

In [56]:
ar.min() #will give min no.

1

In [57]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [60]:
ar.reshape((9,))# means (9,0) ma reshape krdo

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [62]:
ar


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
ar1=np.array([[1, 21, 3],
       [4, 15, 16],
       [7, 18, 9]])
ar1

array([[ 1, 21,  3],
       [ 4, 15, 16],
       [ 7, 18,  9]])

In [64]:
ar+ar1

array([[ 2, 23,  6],
       [ 8, 20, 22],
       [14, 26, 18]])

In [65]:
ar*ar1

array([[  1,  42,   9],
       [ 16,  75,  96],
       [ 49, 144,  81]])

In [66]:
np.sqrt(ar)# will give sqrt of every member


array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [67]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
np.where(ar>5) # shall return the tuple of array(giving the index of no,>5)
# hr axis ke liye 1tuple dega

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [69]:
type(np.where(ar>5))

tuple

In [70]:
np.count_nonzero(ar)

9

In [71]:
np.nonzero(ar) # will give indexes where non zero is present

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [72]:
ar[1,2]=0


In [73]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1, 2], dtype=int64))

In [74]:
import sys


In [75]:
py_ar=[2,3,65,7]

In [76]:
np_ar=np.array(py_ar)


***Check The memory space occupied by numpy***

In [77]:
sys.getsizeof(1)*len(py_ar) # no.of bytes one occupy*no.of elements in arr

112

In [78]:
np_ar.itemsize*np_ar.size # no.of bytes one occupy*no.of elements in arr

16

In [79]:
np_ar.tolist() # numpy array ki python list banadega

[2, 3, 65, 7]

In [80]:
sys.getsizeof(2)*len(np_ar)

112