In [1]:
print("Hello World")

Hello World


In [2]:
import numpy as np


In [3]:
myarr=np.array([[1,2,3,4,4]],np.int64)

In [4]:
print(myarr)

[[1 2 3 4 4]]


In [5]:
myarr[0,1]

2

In [6]:
myarr.shape


(1, 5)

In [7]:
myarr.dtype


dtype('int64')

In [8]:
myarr


array([[1, 2, 3, 4, 4]], dtype=int64)

In [9]:
myarr[0,1]=32

In [10]:
myarr

array([[ 1, 32,  3,  4,  4]], dtype=int64)

In [11]:
# 5 Methods to create numpy array



**Array Creation : Conversion from other Python Structures **

In [12]:
listarray=np.array([[1,2,3],[3,4,56],[5,6,3]])
listarray

array([[ 1,  2,  3],
       [ 3,  4, 56],
       [ 5,  6,  3]])

In [13]:
listarray.shape


(3, 3)

In [14]:
listarray.size #will give no. of elements in array

9

In [15]:
listarray.dtype


dtype('int32')

In [18]:
#zeros create matrix or array 2 dimensional

zeros=np.zeros((2,5))
zeros


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
zeros.shape


(2, 5)

In [21]:
zeros.size

10

In [22]:
zeros.dtype

dtype('float64')

In [23]:
rng=np.arange(16)
rng


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [27]:
# linspace 1=>starting no. 2=>ending no. 3=>how many no. u want   --will give equally spaced elements
lspace=np.linspace(1,9,4)
lspace

array([1.        , 3.66666667, 6.33333333, 9.        ])

In [28]:
empty=np.empty((4,6)) #empty gives empty array with random no.s
empty

array([[6.95237839e-310, 6.95237838e-310, 0.00000000e+000,
        1.21590359e-311, 1.21659854e-311, 4.94065646e-324],
       [0.00000000e+000, 0.00000000e+000, 4.04738577e-320,
        0.00000000e+000, 1.23022346e-321, 1.21659788e-311],
       [9.34600963e-307, 1.86921143e-306, 0.00000000e+000,
        1.21659788e-311, 8.45610231e-307, 9.34601642e-307],
       [8.45590539e-307, 5.48412867e-322, 1.78022342e-306,
        8.06635958e-308, 1.42410974e-306,             nan]])

In [29]:
emp_like=np.empty_like(lspace) # empty elements create kreyga with previous array to increase efficiency
emp_like

array([1.        , 3.66666667, 6.33333333, 9.        ])

In [31]:
ide=np.identity(45) # will give unit matrix of 45*45
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [32]:
ide.shape

(45, 45)

In [33]:
ide.size

2025

In [34]:
arr=np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [37]:
arr.reshape(3,33) #will give resize of array but 33*3 should be == 99

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [39]:
arr=arr.ravel()
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [40]:
arr.shape


(99,)

In [41]:
arr.size

99

In [43]:
x=[[1,2,3],[4,5,6],[7,8,9]]
ar=np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
ar.shape

(3, 3)

In [45]:
ar.size

9

In [47]:
ar.sum(axis=0) #will give the sum of columns

array([12, 15, 18])

In [48]:
ar.sum(axis=1) # will give the sum of rows

array([ 6, 15, 24])

In [49]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [51]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
for items in ar.flat: # will print all elements of 2D array
    print(items)

1
2
3
4
5
6
7
8
9


In [53]:
ar.ndim # will give no. of dimensions

2

In [54]:
ar.nbytes # how many bytes the array is consuming

36

In [55]:
one=np.array([1,3,5,4,433])
one

array([  1,   3,   5,   4, 433])

In [56]:
one.argmax() #will give the index of max element

4

In [57]:
one.argmin() #will give the index of max element

0

In [58]:
one.argsort() # will tell that index no. should be at this position inorder to sort

array([0, 1, 3, 2, 4], dtype=int64)

In [59]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
ar.argmin() # ye array ko pura seedha krkyphir check kry ga ke konsy index pr min no ha

0

In [61]:
ar.argmax()# ye array ko pura seedha krkyphir check kry ga ke konsy index pr max no ha

8

In [62]:
ar.argmax(axis=0) #will check column wise

array([2, 2, 2], dtype=int64)

In [63]:
ar.argmin(axis=1) #will check row wise

array([0, 0, 0], dtype=int64)

In [64]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [66]:
ar.argmin()#will give index

0

In [67]:
ar.min() #will give min no.

1

In [68]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [73]:
ar.reshape((9,))# means (9,0) ma reshape krdo

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [75]:
ar


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
ar1=np.array([[1, 21, 3],
       [4, 15, 16],
       [7, 18, 9]])
ar1

array([[ 1, 21,  3],
       [ 4, 15, 16],
       [ 7, 18,  9]])

In [77]:
ar+ar1

array([[ 2, 23,  6],
       [ 8, 20, 22],
       [14, 26, 18]])

In [78]:
ar*ar1

array([[  1,  42,   9],
       [ 16,  75,  96],
       [ 49, 144,  81]])

In [79]:
np.sqrt(ar)# will give sqrt of every member


array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [80]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
np.where(ar>5) # shall return the tuple of array(giving the index of no,>5)
# hr axis ke liye tuple dega

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [83]:
type(np.where(ar>5))

tuple

In [85]:
np.count_nonzero(ar)

9

In [86]:
np.nonzero(ar) # will give indexes where non zero is present

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [87]:
ar[1,2]=0


In [88]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1, 2], dtype=int64))