In [1]:
l=range(1000000)

In [3]:
import numpy as np
d=np.arange(1000000)

In [4]:
%time for i in range(1,10): r=[x*2 for x in l]

CPU times: total: 922 ms
Wall time: 911 ms


In [5]:
%time for i in range(1,10): r=d*2

CPU times: total: 31.2 ms
Wall time: 31 ms


In [10]:
x=np.zeros((4,4))
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
np.empty((7,7))

array([[1.03208477e-311, 1.03206008e-311, 4.77295198e+180,
        7.04134365e-009, 6.17469347e-114, 4.83245960e+276,
        1.65172546e-076],
       [1.05089883e-153, 3.26209314e-086, 5.28595556e-085,
        2.08925303e-076, 2.59345414e+161, 6.03395497e-154,
        1.04884745e-153],
       [6.01347048e-154, 3.24245676e-086, 6.82129758e-038,
        1.52031679e-047, 6.03095095e-154, 6.01347002e-154,
        5.39958170e+213],
       [3.58251229e+246, 9.19596581e+170, 7.57862409e-010,
        1.67709469e+243, 5.38970828e+228, 3.42549581e+214,
        2.17162117e+214],
       [2.87903286e-152, 7.35167805e+223, 5.26988966e+222,
        3.74165277e+233, 9.16649989e-072, 2.17151199e+214,
        6.45967520e+270],
       [7.35958529e+223, 7.04134408e-009, 2.00127564e+161,
        1.68498995e+190, 7.76651224e+141, 1.26088822e+232,
        2.38345081e+180],
       [6.45346017e+270, 2.25563599e-153, 8.90429141e+247,
        1.26449903e-118, 2.17151199e+214, 2.03471798e-110,
        1.27617599

In [13]:
l=[1,4,5,7]
np.array(l)

array([1, 4, 5, 7])

In [14]:
np.arange(1,100,10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [15]:
x.shape

(4, 4)

In [16]:
x=np.zeros((10,10))

In [17]:
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [18]:
x.shape

(10, 10)

In [19]:
x.reshape(4,25)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [26]:
y=x.reshape(2,2,5,5)

In [21]:
y=dtype


NameError: name 'dtype' is not defined

In [22]:
y.dtype

NameError: name 'y' is not defined

In [23]:
x.dtype

dtype('float64')

In [24]:
x.ndim

2

In [27]:
y.ndim

4

In [28]:
a=np.random.randn((10))

In [29]:
b=np.random.randn((10))

In [30]:
a

array([-0.29764242, -0.19772242,  1.14785329, -1.21153047, -1.26750298,
        0.61644186,  0.13689807,  0.36077019,  0.84870284,  1.17440281])

In [31]:
b

array([-0.12785142, -1.24715464, -1.02645937, -0.10164239, -0.94616817,
       -0.96506536,  0.27325578, -0.12841818, -0.55680855,  1.08917369])

In [32]:
a+b

array([-0.42549384, -1.44487706,  0.12139392, -1.31317285, -2.21367115,
       -0.3486235 ,  0.41015385,  0.232352  ,  0.29189429,  2.2635765 ])

In [33]:
a-b

array([-0.169791  ,  1.04943222,  2.17431266, -1.10988808, -0.32133481,
        1.58150722, -0.13635771,  0.48918837,  1.40551139,  0.08522912])

In [34]:
a/b

array([ 2.32803379,  0.15853881, -1.11826471, 11.91953991,  1.33961702,
       -0.63875659,  0.50098876, -2.80933879, -1.52422738,  1.07825117])

In [35]:
a*2

array([-0.59528484, -0.39544484,  2.29570658, -2.42306094, -2.53500596,
        1.23288371,  0.27379615,  0.72154037,  1.69740568,  2.34880562])

In [36]:
1/a

array([-3.35973617, -5.05759541,  0.87119147, -0.82540227, -0.78895278,
        1.62221301,  7.30470474,  2.77184767,  1.17826871,  0.8514966 ])

In [37]:
a>0

array([False, False,  True, False, False,  True,  True,  True,  True,
        True])

In [38]:
a[a>0]

array([1.14785329, 0.61644186, 0.13689807, 0.36077019, 0.84870284,
       1.17440281])

In [39]:
a<0

array([ True,  True, False,  True,  True, False, False, False, False,
       False])

In [40]:
a[a<0]

array([-0.29764242, -0.19772242, -1.21153047, -1.26750298])

In [42]:
a==0

True

In [45]:
x=np.array([1,3,6,3,8])

In [46]:
x

array([1, 3, 6, 3, 8])

In [47]:
x[4]

8

In [49]:
x[[1,2]]

array([3, 6])

In [50]:
x[0]

1

In [51]:
x=np.empty((3,3))

In [52]:
x

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
       [1.15710427e-306, 1.78019082e-306, 1.42419938e-306],
       [7.56603881e-307, 8.45603440e-307, 3.49698923e-317]])

In [53]:
x[0][2]

1.6912109553714024e-306

In [54]:
x[1][1]

1.780190822459647e-306

In [59]:
x=np.ones((10,10))

In [60]:
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [61]:
x[1:10:2]

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [63]:
x[::,0:2]

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [65]:
x=np.ones((5,5))
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [66]:
x[1:-1,1:-1]=0

In [67]:
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [68]:
x=np.array([10,9,8,6,11])

In [69]:
np.sqrt(x)

array([3.16227766, 3.        , 2.82842712, 2.44948974, 3.31662479])

In [70]:
np.power(x,2)

array([100,  81,  64,  36, 121], dtype=int32)

In [73]:
y=[7,2,3,11,-1]

In [74]:
np.maximum(x,y)

array([10,  9,  8, 11, 11])

In [75]:
salary=np.array([0,400000,-2,90000,70000])
np.where(salary<=0,25000,salary)



array([ 25000, 400000,  25000,  90000,  70000])

In [77]:
np.where(salary<=0,"Invalid","Valid")

array(['Invalid', 'Valid', 'Invalid', 'Valid', 'Valid'], dtype='<U7')

In [78]:
x=np.array([10,9,7,10,7])

In [79]:
x.mean()

8.6

In [80]:
x.cumsum()

array([10, 19, 26, 36, 43], dtype=int32)

In [81]:
x.cumprod()

array([   10,    90,   630,  6300, 44100], dtype=int32)

In [82]:
y=x>6

In [83]:
y

array([ True,  True,  True,  True,  True])

In [84]:
y.sum()

5

In [85]:
y.any()

True

In [86]:
y.all()

True

In [87]:
y=x>7

In [88]:
y

array([ True,  True, False,  True, False])

In [89]:
y.sum()

3

In [90]:
y.any()

True

In [91]:
y.all()

False

In [92]:
x

array([10,  9,  7, 10,  7])

In [93]:
x.sort()

In [94]:
x

array([ 7,  7,  9, 10, 10])

In [95]:
x

array([ 7,  7,  9, 10, 10])

In [103]:
u,z=np.unique(x,return_counts=True)

In [107]:
u,z

(array([ 7,  9, 10]), array([2, 1, 2], dtype=int64))

In [106]:
dict(zip(u,z))

{7: 2, 9: 1, 10: 2}

In [108]:
np.unique(x)

array([ 7,  9, 10])

In [109]:
a=np.where(x>7)

(array([2, 3, 4], dtype=int64),)

In [114]:
x=np.random.randn(2,3)

In [116]:
y=np.random.randn(3,2)

In [117]:
x.dot(y)

array([[-0.04039984,  2.41521667],
       [ 0.19533821,  4.66784046]])

In [118]:
x.transpose()

array([[-0.04305873,  0.45806877],
       [ 0.69787907,  1.40593901],
       [ 0.49994066,  1.0047648 ]])

In [119]:
x

array([[-0.04305873,  0.69787907,  0.49994066],
       [ 0.45806877,  1.40593901,  1.0047648 ]])

In [120]:
x.trace()

1.362880281238101

In [121]:
y.trace()

2.805380914320444