# Numpy For Data Science

In [1]:
import numpy as np


In [4]:
ar=np.array([[1,23,4,65]],np.int64)

In [5]:
ar


array([[ 1, 23,  4, 65]], dtype=int64)

In [6]:
ar

array([[ 1, 23,  4, 65]], dtype=int64)

In [7]:
print(ar)

[[ 1 23  4 65]]


In [8]:
ar.shape

(1, 4)

In [9]:
ar.size

4

In [10]:
ar[0,3]

65

In [12]:
ar[0,1]=44

In [13]:
ar

array([[ 1, 44,  4, 65]], dtype=int64)

## Numpy array methods

In [14]:
larray=np.array([[1,2,3],[4,5,6],[7,8,9]])
larray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
larray.shape

(3, 3)

In [16]:
larray.size

9

In [17]:
larray.dtype

dtype('int32')

In [18]:
ar.dtype

dtype('int64')

In [19]:
zeros=np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
zeros.shape

(2, 3)

In [21]:
zeros.size

6

In [22]:
zeros.dtype

dtype('float64')

In [24]:
rng=np.arange(16)

In [25]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [29]:
lspace=np.linspace(2,10,3)

In [48]:
lspace

array([ 2.,  6., 10.])

In [49]:
empty1=np.empty((3,3))

In [50]:
empty1

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 5.73116149e-321],
       [1.10501794e+185, 2.37799517e-301, 2.26361790e-301]])

In [51]:
empty.dtype

dtype('float64')

In [52]:
emp_like=np.empty_like(lspace)

In [53]:
emp_like

array([ 2.,  6., 10.])

In [58]:
ide=np.identity(4)

In [59]:
ide

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [60]:
ide.shape

(4, 4)

In [61]:
ide.size

16

In [62]:
arr=np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [63]:
arr.reshape((3,33))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [66]:
arr.reshape((99,))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [67]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [68]:
arr.shape

(99,)

In [69]:
arr.size

99

In [70]:
ar

array([[ 1, 44,  4, 65]], dtype=int64)

In [71]:
ar=np.array(larray)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
ar.sum(axis=0)

array([12, 15, 18])

In [73]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [74]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [75]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [77]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
for items in ar.flat:
    print(items)
    

1
2
3
4
5
6
7
8
9


In [78]:
ar.ndim

2

In [79]:
ar.nbytes

36

In [80]:
one=np.array([1,2,43,44])
one

array([ 1,  2, 43, 44])

In [81]:
one.argmax()

3

In [82]:
one.argmin()

0

In [83]:
one.max()

44

In [84]:
one.min(
)

1

In [85]:
one.argsort()

array([0, 1, 2, 3], dtype=int64)

In [86]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [87]:
ar.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [88]:
ar.argmin(axis=1)

array([0, 0, 0], dtype=int64)

In [89]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [90]:
ar.max()


9

In [91]:
ar.min()

1

In [92]:
ar.argmin()

0

In [93]:
ar.argmax()

8

In [94]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [95]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [97]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [98]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [99]:
arr1=np.array([[43,3,5],[4,5,6],[57,76,95]])
arr1

array([[43,  3,  5],
       [ 4,  5,  6],
       [57, 76, 95]])

In [100]:
ar+arr1

array([[ 44,   5,   8],
       [  8,  10,  12],
       [ 64,  84, 104]])

In [101]:
ar*arr1

array([[ 43,   6,  15],
       [ 16,  25,  36],
       [399, 608, 855]])

In [102]:
np.sqrt(ar*arr1)

array([[ 6.55743852,  2.44948974,  3.87298335],
       [ 4.        ,  5.        ,  6.        ],
       [19.97498436, 24.65765601, 29.24038303]])

In [103]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [104]:
np.where(ar>5)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [105]:
type(np.where(ar>5))

tuple

In [106]:
np.nonzero(arr)

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
        35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
        52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
        69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
        86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98], dtype=int64),)

In [107]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [108]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [109]:
np.count_nonzero(ar)

9

In [110]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [111]:
import sys

In [112]:
py_arr=[3,4,5,2]
np_arr=np.array(py_arr)

In [120]:
sys.getsizeof(1)*len(py_arr)

112

In [121]:
sys.getsizeof(1)

28

In [115]:
np_arr.itemsize*np_arr.size

16

In [116]:
np_arr.itemsize

4

In [118]:
np_arr.tolist()

[3, 4, 5, 2]

In [119]:
np_arr.itemsize*np_arr.size

16

# From Youtube

In [1]:
import numpy as np
a=np.array([1,2,3])

In [2]:
a

array([1, 2, 3])

In [3]:
a[0]

1

In [4]:
a[1]

2

In [5]:
a.ndim

1

In [6]:
a.itemsize #(will give the size of items in a list => 4 bytes)

4

In [7]:
a.dtype

dtype('int32')

In [14]:
a=np.array([[1,2],[3,4],[5,6]],dtype=float)

In [15]:
a.dtype

dtype('float64')

In [16]:
a.itemsize  #(will give the size of items in a list => 8 bytes)

8

In [17]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [19]:
a.size #total number of elements

6

In [22]:
a.shape #will show shape of array

(3, 2)

In [23]:
b=np.array([[1,2],[3,4],[5,6]],dtype=complex)

In [24]:
b

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [25]:
a.itemsize

8

In [26]:
a.size

6

In [27]:
a.shape

(3, 2)

In [29]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [31]:
l=range(5)

In [32]:
l

range(0, 5)

In [33]:
l[0],l[1],l[2]

(0, 1, 2)

In [34]:
b=np.arange(1,5)

In [35]:
b

array([1, 2, 3, 4])

In [36]:
np.arange(1,5,2)

array([1, 3])

In [39]:
np.linspace(1,5,10) #will geenerate linearly spaced 10 numbers between 1 and 5 

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [40]:
a.reshape(6,1)

array([[1.],
       [2.],
       [3.],
       [4.],
       [5.],
       [6.]])

In [42]:
a.reshape(2,3)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [43]:
a.ravel() #to make array flatten or 1 dimensional

array([1., 2., 3., 4., 5., 6.])

In [44]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [45]:
a.min()

1.0

In [46]:
a.max()

6.0

In [47]:
a.sum()

21.0

In [49]:
a.sum(axis=0) #0 means y axis

array([ 9., 12.])

In [51]:
a.sum(axis=1) # 1 means x axis

array([ 3.,  7., 11.])

In [53]:
np.sqrt(a) # will give sqrt of each element

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [54]:
np.std(a)

1.707825127659933

In [55]:
a=np.array([[1,2],[3,4]])

In [56]:
b=np.array([[5,6],[7,8]])

In [57]:
a

array([[1, 2],
       [3, 4]])

In [58]:
b

array([[5, 6],
       [7, 8]])

In [59]:
a+b

array([[ 6,  8],
       [10, 12]])

In [60]:
a-b

array([[-4, -4],
       [-4, -4]])

In [61]:
a*b

array([[ 5, 12],
       [21, 32]])

In [62]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [63]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [64]:
np.full((3,4),2)

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

# Numpy slicing and stacking

In [65]:
a=np.array([6,7,8])
a[0]


6

In [66]:
a[0:2]

array([6, 7])

In [67]:
a[-1]

8

In [68]:
a[-1:-3]

array([], dtype=int32)

In [70]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [71]:
a[1,2]

6

In [72]:
a[2,1]

8

In [73]:
a[0:2,2]

array([3, 6])

In [74]:
a[0:2,1]

array([2, 5])

In [75]:
a[0:3,1]

array([2, 5, 8])

In [76]:
a[0:3,0]

array([1, 4, 7])

In [77]:
a[-1]

array([7, 8, 9])

In [78]:
a[-1,0:2]

array([7, 8])

In [79]:
a[:,1:3] 

array([[2, 3],
       [5, 6],
       [8, 9]])

In [80]:
a.flat

In [82]:
for row in a:
    print(row)

[1 2 3]
[4 5 6]
[7 8 9]


In [83]:
for row in a.flat:
    print(row)

1
2
3
4
5
6
7
8
9


In [86]:
a=np.arange(6).reshape(3,2)
b=np.arange(6,12).reshape(3,2)

In [87]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [88]:
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [91]:
np.vstack((a,b))# 1 array ky oper 1 or array rkh di

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [92]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [95]:
a=np.arange(30).reshape(2,15)

In [96]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [97]:
result=np.hsplit(a,3)

In [98]:
result

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [99]:
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [100]:
result[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [101]:
result[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [102]:
np.vsplit(a,2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [106]:
result1=np.vsplit(a,2)

In [108]:
result1[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [109]:
result1[1]

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [110]:
a=np.arange(12).reshape(3,4)

In [111]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [112]:
b=a>4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [113]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [114]:
a[b]=-1

In [115]:
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])